import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store-provider";
import Footer from "@/components/layout/footer";
import { CartProvider } from '@/context/cart-context';
import CartPreview from "@/components/layout/cart-preview";
import MainNavigation from "@/components/layout/navigation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) => {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <CartProvider>
            <main className="">
              <MainNavigation className="z-50 p-4 sticky top-0 bg-white/90 backdrop-blur-sm nav-border-reveal"/>
              {children}
              <Footer />
              <CartPreview />
            </main>
          </CartProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
